<?php
/**
 * InvoiceType
 *
 * PHP version 5
 *
 * @category Class
 * @package  MimoGraphix\Uctoplus
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Moje Účto+ API
 *
 * API description in Markdown.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: helpdesk@uctoplus.sk
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MimoGraphix\Uctoplus\Models;
use \MimoGraphix\Uctoplus\ObjectSerializer;

/**
 * InvoiceType Class Doc Comment
 *
 * @category Class
 * @description * &#x60;1&#x60; - Invocie * &#x60;2&#x60; - Proforma Invoice * &#x60;3&#x60; - Dobropis * &#x60;4&#x60; - Price Quotation * &#x60;5&#x60; - Dodací list * &#x60;6&#x60; - VAT Proof
 * @package  MimoGraphix\Uctoplus
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class InvoiceType
{
    /**
     * Possible values of this enum
     */
    const INVOICE = 'TYPE_INVOICE';
    const PROFORMA_INVOICE = 'TYPE_PROFORMA_INVOICE';
    const DOBROPIS = 'TYPE_DOBROPIS';
    const PRICE_QUOTATION = 'TYPE_PRICE_QUOTATION';
    const DODACI_LIST = 'TYPE_DODACI_LIST';
    const VAT_PROOF = 'TYPE_VAT_PROOF';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::INVOICE,
            self::PROFORMA_INVOICE,
            self::DOBROPIS,
            self::PRICE_QUOTATION,
            self::DODACI_LIST,
            self::VAT_PROOF,
        ];
    }
}


